version: "3.7"
services:
  rstudio:
    image: your-project-name:latest
    build:
      context: docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
    volumes:
      - .:/home/rstudio/your-project-name
