FROM rocker/tidyverse:4.0.2

# Install packages
# RUN install2.r pkgname1 pkgname2

# Set Global Options
COPY --chown=rstudio:rstudio .config/rstudio/rstudio-prefs.json /home/rstudio/.config/rstudio/rstudio-prefs.json
